"""Constants for the Agent Orchestrator MCP Server."""

# Concurrency limits
MAX_AGENTS = 5
DEFAULT_SEMAPHORE_LIMIT = 5

# HTTP timeouts
DEFAULT_HTTP_TIMEOUT = 30.0

# Logfire configuration
LOGFIRE_PROJECT_NAME = "ct-dev-agent-orchestrator"
LOGFIRE_SERVICE_NAME = "mcp-server"

# Response formatting
TOOL_RESPONSE_SUCCESS = "success"
TOOL_RESPONSE_ERROR = "error"

# Session management
SESSION_TIMEOUT = 30.0
MAX_RETRY_ATTEMPTS = 3
RETRY_DELAY = 1.0

# API endpoints
OPENCODE_API_BASE_URL = "http://localhost:8080"
OPENCODE_API_TIMEOUT = 30.0

# Error messages
ERROR_SESSION_NOT_FOUND = "Session not found"
ERROR_AGENT_NOT_FOUND = "Agent not found"
ERROR_INVALID_REQUEST = "Invalid request"
ERROR_INTERNAL_SERVER = "Internal server error"

# Additional constants for utils/__init__.py compatibility
DEFAULT_MESSAGE_TIMEOUT = 30.0
MAX_RETRIES = 3
HEARTBEAT_INTERVAL = 30.0
SESSION_CLEANUP_INTERVAL = 300.0
API_BASE_URL = "http://localhost:8080"  # Alias for OPENCODE_API_BASE_URL
DEFAULT_PROJECT_PATH = "/home/auctor/dev"

# Delegation constants
DEFAULT_DELEGATOR = "Main Agent"
DELEGATION_EVENT_DELEGATED = "DELEGATED"
DELEGATION_EVENT_COMPLETED = "COMPLETED"
DELEGATION_EVENT_FAILED = "FAILED"
AGENT_EXECUTE_ENDPOINT = "/execute"
ERROR_EXECUTION_TIMEOUT = "Execution timeout"
TABLE_DELEGATIONS = "delegations"
TABLE_DELEGATION_EVENTS = "delegation_events"
TABLE_TASKS = "tasks"

# OpenCode Service specific constants
# Service configuration
OPENCODE_MAX_AGENTS = 5
OPENCODE_BASE_PORT = 8000
OPENCODE_SERVER_HOST = "localhost"

# Timeouts (in seconds)
OPENCODE_MAX_WAIT_TIMEOUT = 5
OPENCODE_HEALTH_CHECK_TIMEOUT = 8
OPENCODE_HEALTH_CHECK_METHOD_TIMEOUT = 10
OPENCODE_HTTP_REQUEST_TIMEOUT = 1.0
OPENCODE_PROCESS_TERMINATION_TIMEOUT = 5
OPENCODE_FORCE_KILL_TIMEOUT = 2
OPENCODE_HTTP_CLIENT_TIMEOUT = 30.0

# API Client specific constants
OPENCODE_CLIENT_TIMEOUT = 30.0
OPENCODE_PROCESS_CLEANUP_TIMEOUT = 3
OPENCODE_GRACEFUL_SHUTDOWN_TIMEOUT = 5
OPENCODE_HEALTH_CHECK_CLIENT_TIMEOUT = 5.0
OPENCODE_MESSAGE_SENDING_TIMEOUT = 300.0
OPENCODE_CPU_PERCENT_INTERVAL = 0.1
OPENCODE_ASYNCIO_SLEEP_DELAY = 0.5
OPENCODE_DEADLINE_TIMEOUT = 15.0

# API Endpoints
OPENCODE_ENDPOINT_INITIALIZE = "/initialize"
OPENCODE_ENDPOINT_ACTIVATE_PROJECT = "/activate_project"
OPENCODE_ENDPOINT_GET_SYMBOLS_OVERVIEW = "/get_symbols_overview"
OPENCODE_ENDPOINT_FIND_SYMBOL = "/find_symbol"
OPENCODE_ENDPOINT_FIND_REFERENCING_SYMBOLS = "/find_referencing_symbols"
OPENCODE_ENDPOINT_READ_FILE = "/read_file"
OPENCODE_ENDPOINT_CREATE_TEXT_FILE = "/create_text_file"
OPENCODE_ENDPOINT_REPLACE_LINES = "/replace_lines"
OPENCODE_ENDPOINT_INSERT_AT_LINE = "/insert_at_line"
OPENCODE_ENDPOINT_DELETE_LINES = "/delete_lines"
OPENCODE_ENDPOINT_REPLACE_REGEX = "/replace_regex"
OPENCODE_ENDPOINT_SEARCH_FOR_PATTERN = "/search_for_pattern"
OPENCODE_ENDPOINT_LIST_DIR = "/list_dir"
OPENCODE_ENDPOINT_FIND_FILE = "/find_file"

# CLI Commands
OPENCODE_CMD_ACTIVATE_PROJECT = "activate_project"
OPENCODE_CMD_INITIALIZE = "initialize"
OPENCODE_CMD_STOP = "stop"
OPENCODE_CMD_START = "start"

# Server configuration
OPENCODE_SERVER_WORKERS = 1
OPENCODE_SERVER_RELOAD = False
OPENCODE_SERVER_HOST_DEFAULT = "localhost"
OPENCODE_SERVER_PORT_DEFAULT = 8000
OPENCODE_SERVER_LOG_LEVEL = "info"
